# Qwen2.5 Moroccan Law — Load from Drive Link & Test
No manual mounting needed. Just run cells top-to-bottom.

In [1]:
import torch

print('CUDA available:', torch.cuda.is_available())
if torch.cuda.is_available():
    print('GPU:', torch.cuda.get_device_name(0))
    print('VRAM:', round(torch.cuda.get_device_properties(0).total_memory / 1e9, 1), 'GB')
else:
    raise RuntimeError('No GPU found. Runtime > Change runtime type > T4 GPU')

CUDA available: True
GPU: Tesla T4
VRAM: 15.6 GB

In [2]:
%%capture
!pip install "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git"
!pip install --no-deps trl peft accelerate bitsandbytes
!pip install -q gdown

In [3]:
import gdown, os

FOLDER_ID  = '189nkqTWAi0Mf620RfVL_eMnlU6GnqTPW'
LOCAL_DIR  = '/content/lora-adapter'

# Download all adapter files from the shared Drive folder
print('Downloading adapter from Drive...')
gdown.download_folder(
    id=FOLDER_ID,
    output=LOCAL_DIR,
    quiet=False,
    use_cookies=False,
)

# gdown sometimes nests an extra subfolder — find the real adapter root
def find_adapter_root(base):
    """Walk down single-child dirs until we find adapter_config.json."""
    for root, dirs, files in os.walk(base):
        if 'adapter_config.json' in files:
            return root
    return None

ADAPTER_PATH = find_adapter_root(LOCAL_DIR)
assert ADAPTER_PATH, (
    'adapter_config.json not found after download. '
    'Check that the Drive folder contains your LoRA adapter files.'
)

print('Adapter ready at:', ADAPTER_PATH)
print('Files:', os.listdir(ADAPTER_PATH))

Downloading adapter from Drive...

Retrieving folder contents

Retrieving folder 19GVT-A4KiV1BWPLbeb1L-OcgJSLDpBrp checkpoints
Retrieving folder 1CuQ-EuZk1qQQnNST4UdI-sfJNDdfxvgW checkpoint-850
Processing file 11GLS8j5AADenGTlSE_4LvHhjtVxCecpU adapter_config.json
Processing file 1SpyrXhEVZLNkgFhoEDU6vHrPsJ_lkMgs adapter_model.safetensors
Processing file 1xzRAdx0QwA_NYDne1FRQ591kM0X01Toi chat_template.jinja
Processing file 19Dzd05tVpG1Ee1zDYJUUx7nblwP4tID2 optimizer.pt
Processing file 18MesBNXeMe2xyoIDu5o1KFQFWLjltKkn README.md
Processing file 1RLxNBpAtaxFGcgbbLnjD8qwN_AmScO1c rng_state.pth
Processing file 1NGL05cE_fkcrxZOcyhS_mL60DM3t-1h5 scaler.pt
Processing file 1S1ehnaJV9BXbmX_Z8Bmq-CzIE2_4ev_Z scheduler.pt
Processing file 1pSr96FOAgUXk8oS3oQdFWqRLVhR3e7AW tokenizer_config.json
Processing file 11g17uEjQSPYyXmG8f__9faowNEbO9YWF tokenizer.json
Processing file 1k7JTdOg0tW524K4pYx5-8l0LVUh7RRIp trainer_state.json
Processing file 10Hx5V4g6lUICqk7Wc3zYISUydFaG-AVx training_args.bin
Retrieving folder 1AJgSRrFvoT6pLp_cBT6Jgqtzd0Lcvx5I checkpoint-875
Processing file 1G-Fl1p2b8OP6XVL3PSgPQD352UcQq2h6 adapter_config.json
Processing file 1KTFADe_nc_2eAIkTxZkC_fHpkGtAaLi1 adapter_model.safetensors
Processing file 1Wb_e6G8J4O-azSUD5I1y2WO9sb2zlA_n chat_template.jinja
Processing file 1KdFJYX4zOBwq50uk0iZAeE7hG2aqDAh- optimizer.pt
Processing file 10EnDfM-zKGR0PqFzog2AGVEFrbTQvQH_ README.md
Processing file 1eqtLJCBGaMWf0Eda0EL2M19ugcfTPxNz rng_state.pth
Processing file 1XGQhhC48PdjiaSlY8rX5Sv71J8Z9c8Is scaler.pt
Processing file 1L_0NkN3Hg2gLSXPn7irR065AF7SJxYuP scheduler.pt
Processing file 1PAQ2O5u0IOAHVfXrzmGQF2pV41oPwH6G tokenizer_config.json
Processing file 1AzbOxS0-YXPIYRwy_O2UYj6hFa53wG0I tokenizer.json
Processing file 1ZNA8z3W0b1wb6DnGJxaBwG6QN7KvHjYE trainer_state.json
Processing file 1BDx0jlSBVQaPK1MecocXiW94xY4sePzZ training_args.bin
Retrieving folder 1lRp4zmhmJ2duCNy7OlUZ2K_SjkcLQzK1 checkpoint-897
Processing file 1sNwc2h4K5gVNchctBW68cFaAxNR8iH16 adapter_config.json
Processing file 1LVykXySWHDiAm165QKd2F4hYOiQ917X9 adapter_model.safetensors
Processing file 1DQ87vfl3m4u3bmr_oiYg0OtJ2rFrpCUl chat_template.jinja
Processing file 1RYOwgNGi-HClUSMRfjILpqRWsNuONwC3 optimizer.pt
Processing file 1GEDzsf85GTRHVy1d7MZ3deMyGraKPnhF README.md
Processing file 1J0WSBjARzb_5bI71FTNv8uYHpNl1irng rng_state.pth
Processing file 1r_zhksSw3Hph4Wo-O_BFLc_G0fTy4rQm scaler.pt
Processing file 1Dx0_ouH6deXhOHpSg6-3IqgXJopQoiB7 scheduler.pt
Processing file 1VcCWBEUAiC0MLsKbI-9Jj1SPk6mESLX9 tokenizer_config.json
Processing file 1hTAwoM8C4_slj78WhMXmtaJGxI_9UlqK tokenizer.json
Processing file 117gMNMqm5wktVnjQDLEcqS9S6Lbj4jL8 trainer_state.json
Processing file 1AiAhNaqM8496nCTmsDHFW0EqvsBppSQa training_args.bin
Processing file 1UV-URh534iSkWXnomb5mBsYng-M4dDaG README.md
Retrieving folder 1oQb3puIrcCTgmJpPY1Qem5NFfvYoeqD7 cleaned-data
Processing file 17l6xthb8qRY8nqleRF5fwuxGQezoWFOU moroccan_law_cleaned_all.jsonl
Processing file 1pv3kWHSicb4X35izJEaB-OL1mZeEqFRz moroccan_law_dataset_report.json
Processing file 1dngdQGFJz3U8BTWLWzivsBupJ1M1QXGc moroccan_law_rejected_examples.csv
Processing file 1vr8liqRdHnaQ4_4lX9scVMVKpRZHUM16 moroccan_law_test.jsonl
Processing file 1y2VSa4glvd9E4vvsk43kR2S7c77lTxy_ moroccan_law_train.jsonl
Processing file 1pTpAXTri-ylDinVWoDrtUkFoWVWOMSz2 moroccan_law_validation.jsonl
Retrieving folder 1-3LnuUbX7TdCQoFcF--hexW6yO0kOmQc lora-adapter
Processing file 1ppp7LLbPE3Uqglucezn5pOnyZ8_hIF40 adapter_config.json
Processing file 18PlMSd40nD_SysAiEeCohtFag15Qx0k2 adapter_model.safetensors
Processing file 1x-I2wlS5f9TUGK3yl091KcmRJaeAIsAm chat_template.jinja
Processing file 17wFbQMUGBHFPKDhflY_YVn66PQkWT_tA README.md
Processing file 16eNjQ4d4nMIX-Cf8S6aBKVzEVXtQFotf tokenizer_config.json
Processing file 1E4xjOawdX0Q-kxoR4x9TqakPhdwwKLDj tokenizer.json
Retrieving folder 1w_5UPdQlFkG4Q4xDnJXSY1H10BSwp-Kz merged-model

Retrieving folder contents completed
Building directory structure
Building directory structure completed
Downloading...
From: https://drive.google.com/uc?id=11GLS8j5AADenGTlSE_4LvHhjtVxCecpU
To: /content/lora-adapter/checkpoints/checkpoint-850/adapter_config.json
100%|██████████| 1.25k/1.25k [00:00<00:00, 4.45MB/s]
Downloading...
From (original): https://drive.google.com/uc?id=1SpyrXhEVZLNkgFhoEDU6vHrPsJ_lkMgs
From (redirected): https://drive.google.com/uc?id=1SpyrXhEVZLNkgFhoEDU6vHrPsJ_lkMgs&confirm=t&uuid=5313b217-647d-450b-8bd2-47ad619e85a0
To: /content/lora-adapter/checkpoints/checkpoint-850/adapter_model.safetensors
100%|██████████| 240M/240M [00:01<00:00, 131MB/s]
Downloading...
From: https://drive.google.com/uc?id=1xzRAdx0QwA_NYDne1FRQ591kM0X01Toi
To: /content/lora-adapter/checkpoints/checkpoint-850/chat_template.jinja
100%|██████████| 2.51k/2.51k [00:00<00:00, 11.0MB/s]
Downloading...
From (original): https://drive.google.com/uc?id=19Dzd05tVpG1Ee1zDYJUUx7nblwP4tID2
From (redirected): https://drive.google.com/uc?id=19Dzd05tVpG1Ee1zDYJUUx7nblwP4tID2&confirm=t&uuid=c8f3c62c-0bed-4eb4-86e5-0b8ea9d2eddf
To: /content/lora-adapter/checkpoints/checkpoint-850/optimizer.pt
100%|██████████| 122M/122M [00:00<00:00, 178MB/s]
Downloading...
From: https://drive.google.com/uc?id=18MesBNXeMe2xyoIDu5o1KFQFWLjltKkn
To: /content/lora-adapter/checkpoints/checkpoint-850/README.md
100%|██████████| 5.25k/5.25k [00:00<00:00, 7.61MB/s]
Downloading...
From: https://drive.google.com/uc?id=1RLxNBpAtaxFGcgbbLnjD8qwN_AmScO1c
To: /content/lora-adapter/checkpoints/checkpoint-850/rng_state.pth
100%|██████████| 14.6k/14.6k [00:00<00:00, 19.9MB/s]
Downloading...
From: https://drive.google.com/uc?id=1NGL05cE_fkcrxZOcyhS_mL60DM3t-1h5
To: /content/lora-adapter/checkpoints/checkpoint-850/scaler.pt
100%|██████████| 1.38k/1.38k [00:00<00:00, 3.92MB/s]
Downloading...
From: https://drive.google.com/uc?id=1S1ehnaJV9BXbmX_Z8Bmq-CzIE2_4ev_Z
To: /content/lora-adapter/checkpoints/checkpoint-850/scheduler.pt
100%|██████████| 1.47k/1.47k [00:00<00:00, 4.28MB/s]
Downloading...
From: https://drive.google.com/uc?id=1pSr96FOAgUXk8oS3oQdFWqRLVhR3e7AW
To: /content/lora-adapter/checkpoints/checkpoint-850/tokenizer_config.json
100%|██████████| 4.56k/4.56k [00:00<00:00, 8.12MB/s]
Downloading...
From: https://drive.google.com/uc?id=11g17uEjQSPYyXmG8f__9faowNEbO9YWF
To: /content/lora-adapter/checkpoints/checkpoint-850/tokenizer.json
100%|██████████| 11.4M/11.4M [00:00<00:00, 41.0MB/s]
Downloading...
From: https://drive.google.com/uc?id=1k7JTdOg0tW524K4pYx5-8l0LVUh7RRIp
To: /content/lora-adapter/checkpoints/checkpoint-850/trainer_state.json
100%|██████████| 39.6k/39.6k [00:00<00:00, 41.9MB/s]
Downloading...
From: https://drive.google.com/uc?id=10Hx5V4g6lUICqk7Wc3zYISUydFaG-AVx
To: /content/lora-adapter/checkpoints/checkpoint-850/training_args.bin
100%|██████████| 5.71k/5.71k [00:00<00:00, 8.53MB/s]
Downloading...
From: https://drive.google.com/uc?id=1G-Fl1p2b8OP6XVL3PSgPQD352UcQq2h6
To: /content/lora-adapter/checkpoints/checkpoint-875/adapter_config.json
100%|██████████| 1.25k/1.25k [00:00<00:00, 2.74MB/s]
Downloading...
From (original): https://drive.google.com/uc?id=1KTFADe_nc_2eAIkTxZkC_fHpkGtAaLi1
From (redirected): https://drive.google.com/uc?id=1KTFADe_nc_2eAIkTxZkC_fHpkGtAaLi1&confirm=t&uuid=3c412871-6827-4439-a55a-2c047a11f4d7
To: /content/lora-adapter/checkpoints/checkpoint-875/adapter_model.safetensors
100%|██████████| 240M/240M [00:02<00:00, 103MB/s]
Downloading...
From: https://drive.google.com/uc?id=1Wb_e6G8J4O-azSUD5I1y2WO9sb2zlA_n
To: /content/lora-adapter/checkpoints/checkpoint-875/chat_template.jinja
100%|██████████| 2.51k/2.51k [00:00<00:00, 6.60MB/s]
Downloading...
From (original): https://drive.google.com/uc?id=1KdFJYX4zOBwq50uk0iZAeE7hG2aqDAh-
From (redirected): https://drive.google.com/uc?id=1KdFJYX4zOBwq50uk0iZAeE7hG2aqDAh-&confirm=t&uuid=745a3e64-4724-4b5d-9b46-185520a9dfe5
To: /content/lora-adapter/checkpoints/checkpoint-875/optimizer.pt
100%|██████████| 122M/122M [00:01<00:00, 80.8MB/s]
Downloading...
From: https://drive.google.com/uc?id=10EnDfM-zKGR0PqFzog2AGVEFrbTQvQH_
To: /content/lora-adapter/checkpoints/checkpoint-875/README.md
100%|██████████| 5.25k/5.25k [00:00<00:00, 15.1MB/s]
Downloading...
From: https://drive.google.com/uc?id=1eqtLJCBGaMWf0Eda0EL2M19ugcfTPxNz
To: /content/lora-adapter/checkpoints/checkpoint-875/rng_state.pth
100%|██████████| 14.6k/14.6k [00:00<00:00, 17.6MB/s]
Downloading...
From: https://drive.google.com/uc?id=1XGQhhC48PdjiaSlY8rX5Sv71J8Z9c8Is
To: /content/lora-adapter/checkpoints/checkpoint-875/scaler.pt
100%|██████████| 1.38k/1.38k [00:00<00:00, 3.87MB/s]
Downloading...
From: https://drive.google.com/uc?id=1L_0NkN3Hg2gLSXPn7irR065AF7SJxYuP
To: /content/lora-adapter/checkpoints/checkpoint-875/scheduler.pt
100%|██████████| 1.47k/1.47k [00:00<00:00, 2.75MB/s]
Downloading...
From: https://drive.google.com/uc?id=1PAQ2O5u0IOAHVfXrzmGQF2pV41oPwH6G
To: /content/lora-adapter/checkpoints/checkpoint-875/tokenizer_config.json
100%|██████████| 4.56k/4.56k [00:00<00:00, 8.04MB/s]
Downloading...
From: https://drive.google.com/uc?id=1AzbOxS0-YXPIYRwy_O2UYj6hFa53wG0I
To: /content/lora-adapter/checkpoints/checkpoint-875/tokenizer.json
100%|██████████| 11.4M/11.4M [00:00<00:00, 37.3MB/s]
Downloading...
From: https://drive.google.com/uc?id=1ZNA8z3W0b1wb6DnGJxaBwG6QN7KvHjYE
To: /content/lora-adapter/checkpoints/checkpoint-875/trainer_state.json
100%|██████████| 40.7k/40.7k [00:00<00:00, 63.5MB/s]
Downloading...
From: https://drive.google.com/uc?id=1BDx0jlSBVQaPK1MecocXiW94xY4sePzZ
To: /content/lora-adapter/checkpoints/checkpoint-875/training_args.bin
100%|██████████| 5.71k/5.71k [00:00<00:00, 7.00MB/s]
Downloading...
From: https://drive.google.com/uc?id=1sNwc2h4K5gVNchctBW68cFaAxNR8iH16
To: /content/lora-adapter/checkpoints/checkpoint-897/adapter_config.json
100%|██████████| 1.25k/1.25k [00:00<00:00, 4.22MB/s]
Downloading...
From (original): https://drive.google.com/uc?id=1LVykXySWHDiAm165QKd2F4hYOiQ917X9
From (redirected): https://drive.google.com/uc?id=1LVykXySWHDiAm165QKd2F4hYOiQ917X9&confirm=t&uuid=dd7532be-8d8a-4740-9504-ead4dce675ac
To: /content/lora-adapter/checkpoints/checkpoint-897/adapter_model.safetensors
100%|██████████| 240M/240M [00:02<00:00, 87.8MB/s]
Downloading...
From: https://drive.google.com/uc?id=1DQ87vfl3m4u3bmr_oiYg0OtJ2rFrpCUl
To: /content/lora-adapter/checkpoints/checkpoint-897/chat_template.jinja
100%|██████████| 2.51k/2.51k [00:00<00:00, 7.16MB/s]
Downloading...
From (original): https://drive.google.com/uc?id=1RYOwgNGi-HClUSMRfjILpqRWsNuONwC3
From (redirected): https://drive.google.com/uc?id=1RYOwgNGi-HClUSMRfjILpqRWsNuONwC3&confirm=t&uuid=fb55e796-00ce-4cf9-83de-732897ecd37a
To: /content/lora-adapter/checkpoints/checkpoint-897/optimizer.pt
100%|██████████| 122M/122M [00:01<00:00, 78.7MB/s]
Downloading...
From: https://drive.google.com/uc?id=1GEDzsf85GTRHVy1d7MZ3deMyGraKPnhF
To: /content/lora-adapter/checkpoints/checkpoint-897/README.md
100%|██████████| 5.25k/5.25k [00:00<00:00, 6.99MB/s]
Downloading...
From: https://drive.google.com/uc?id=1J0WSBjARzb_5bI71FTNv8uYHpNl1irng
To: /content/lora-adapter/checkpoints/checkpoint-897/rng_state.pth
100%|██████████| 14.6k/14.6k [00:00<00:00, 18.8MB/s]
Downloading...
From: https://drive.google.com/uc?id=1r_zhksSw3Hph4Wo-O_BFLc_G0fTy4rQm
To: /content/lora-adapter/checkpoints/checkpoint-897/scaler.pt
100%|██████████| 1.38k/1.38k [00:00<00:00, 5.26MB/s]
Downloading...
From: https://drive.google.com/uc?id=1Dx0_ouH6deXhOHpSg6-3IqgXJopQoiB7
To: /content/lora-adapter/checkpoints/checkpoint-897/scheduler.pt
100%|██████████| 1.47k/1.47k [00:00<00:00, 6.80MB/s]
Downloading...
From: https://drive.google.com/uc?id=1VcCWBEUAiC0MLsKbI-9Jj1SPk6mESLX9
To: /content/lora-adapter/checkpoints/checkpoint-897/tokenizer_config.json
100%|██████████| 4.56k/4.56k [00:00<00:00, 12.8MB/s]
Downloading...
From: https://drive.google.com/uc?id=1hTAwoM8C4_slj78WhMXmtaJGxI_9UlqK
To: /content/lora-adapter/checkpoints/checkpoint-897/tokenizer.json
100%|██████████| 11.4M/11.4M [00:00<00:00, 37.6MB/s]
Downloading...
From: https://drive.google.com/uc?id=117gMNMqm5wktVnjQDLEcqS9S6Lbj4jL8
To: /content/lora-adapter/checkpoints/checkpoint-897/trainer_state.json
100%|██████████| 41.6k/41.6k [00:00<00:00, 33.7MB/s]
Downloading...
From: https://drive.google.com/uc?id=1AiAhNaqM8496nCTmsDHFW0EqvsBppSQa
To: /content/lora-adapter/checkpoints/checkpoint-897/training_args.bin
100%|██████████| 5.71k/5.71k [00:00<00:00, 18.8MB/s]
Downloading...
From: https://drive.google.com/uc?id=1UV-URh534iSkWXnomb5mBsYng-M4dDaG
To: /content/lora-adapter/checkpoints/README.md
100%|██████████| 1.49k/1.49k [00:00<00:00, 4.19MB/s]
Downloading...
From: https://drive.google.com/uc?id=17l6xthb8qRY8nqleRF5fwuxGQezoWFOU
To: /content/lora-adapter/cleaned-data/moroccan_law_cleaned_all.jsonl
100%|██████████| 453k/453k [00:00<00:00, 12.0MB/s]
Downloading...
From: https://drive.google.com/uc?id=1pv3kWHSicb4X35izJEaB-OL1mZeEqFRz
To: /content/lora-adapter/cleaned-data/moroccan_law_dataset_report.json
100%|██████████| 942/942 [00:00<00:00, 3.90MB/s]
Downloading...
From: https://drive.google.com/uc?id=1dngdQGFJz3U8BTWLWzivsBupJ1M1QXGc
To: /content/lora-adapter/cleaned-data/moroccan_law_rejected_examples.csv
100%|██████████| 14.9k/14.9k [00:00<00:00, 16.3MB/s]
Downloading...
From: https://drive.google.com/uc?id=1vr8liqRdHnaQ4_4lX9scVMVKpRZHUM16
To: /content/lora-adapter/cleaned-data/moroccan_law_test.jsonl
100%|██████████| 38.8k/38.8k [00:00<00:00, 38.1MB/s]
Downloading...
From: https://drive.google.com/uc?id=1y2VSa4glvd9E4vvsk43kR2S7c77lTxy_
To: /content/lora-adapter/cleaned-data/moroccan_law_train.jsonl
100%|██████████| 303k/303k [00:00<00:00, 10.0MB/s]
Downloading...
From: https://drive.google.com/uc?id=1pTpAXTri-ylDinVWoDrtUkFoWVWOMSz2
To: /content/lora-adapter/cleaned-data/moroccan_law_validation.jsonl
100%|██████████| 38.0k/38.0k [00:00<00:00, 33.3MB/s]
Downloading...
From: https://drive.google.com/uc?id=1ppp7LLbPE3Uqglucezn5pOnyZ8_hIF40
To: /content/lora-adapter/lora-adapter/adapter_config.json
100%|██████████| 1.25k/1.25k [00:00<00:00, 4.90MB/s]
Downloading...
From (original): https://drive.google.com/uc?id=18PlMSd40nD_SysAiEeCohtFag15Qx0k2
From (redirected): https://drive.google.com/uc?id=18PlMSd40nD_SysAiEeCohtFag15Qx0k2&confirm=t&uuid=0dce85dd-09d8-40da-9d70-1790ad07e14e
To: /content/lora-adapter/lora-adapter/adapter_model.safetensors
100%|██████████| 240M/240M [00:01<00:00, 199MB/s]
Downloading...
From: https://drive.google.com/uc?id=1x-I2wlS5f9TUGK3yl091KcmRJaeAIsAm
To: /content/lora-adapter/lora-adapter/chat_template.jinja
100%|██████████| 2.51k/2.51k [00:00<00:00, 7.68MB/s]
Downloading...
From: https://drive.google.com/uc?id=17wFbQMUGBHFPKDhflY_YVn66PQkWT_tA
To: /content/lora-adapter/lora-adapter/README.md
100%|██████████| 5.25k/5.25k [00:00<00:00, 8.69MB/s]
Downloading...
From: https://drive.google.com/uc?id=16eNjQ4d4nMIX-Cf8S6aBKVzEVXtQFotf
To: /content/lora-adapter/lora-adapter/tokenizer_config.json
100%|██████████| 4.56k/4.56k [00:00<00:00, 6.31MB/s]
Downloading...
From: https://drive.google.com/uc?id=1E4xjOawdX0Q-kxoR4x9TqakPhdwwKLDj
To: /content/lora-adapter/lora-adapter/tokenizer.json
100%|██████████| 11.4M/11.4M [00:00<00:00, 110MB/s]

Adapter ready at: /content/lora-adapter/lora-adapter
Files: ['tokenizer.json', 'adapter_config.json', 'tokenizer_config.json', 'chat_template.jinja', 'README.md', 'adapter_model.safetensors']

Download completed

In [4]:
from unsloth import FastLanguageModel

max_seq_length = 2048

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name=ADAPTER_PATH,
    max_seq_length=max_seq_length,
    dtype=None,
    load_in_4bit=True,
)

FastLanguageModel.for_inference(model)
print('Model loaded and ready.')

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
🦥 Unsloth Zoo will now patch everything to make training faster!

/usr/local/lib/python3.12/dist-packages/peft/config.py:220: UserWarning: Unexpected keyword arguments ['lora_ga_config', 'use_bdlora'] for class LoraConfig, these are ignored. This probably means that you're loading a configuration file that was saved using a higher version of the library and additional parameters have been introduced since. It is highly recommended to upgrade the PEFT version before continuing (e.g. by running `pip install -U peft`).
  warnings.warn(

==((====))==  Unsloth 2026.5.2: Fast Qwen2 patching. Transformers: 5.5.0.
   \\   /|    Tesla T4. Num GPUs = 2. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.10.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = None. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

model.safetensors:   0%|          | 0.00/2.05G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/434 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/271 [00:00<?, ?B/s]

config.json: 0.00B [00:00, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/605 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/614 [00:00<?, ?B/s]

unsloth/Qwen2.5-3B-Instruct-bnb-4bit does not have a padding token! Will use pad_token = <|PAD_TOKEN|>.

Unsloth 2026.5.2 patched 36 layers with 0 QKV layers, 0 O layers and 0 MLP layers.

Model loaded and ready.

## Retrieval-Augmented Generation (RAG) Setup

To enhance the Drive Model's ability to provide accurate and contextually relevant answers, we will integrate Retrieval-Augmented Generation (RAG). This involves:

1.  **Installing RAG Libraries:** Adding `langchain`, `faiss-cpu`, and `sentence-transformers`.
2.  **Loading Legal Documents:** Utilizing the legal documents previously downloaded to create a knowledge base.
3.  **Document Chunking:** Splitting the documents into smaller, manageable chunks.
4.  **Creating Embeddings:** Converting these chunks into numerical representations using an embedding model.
5.  **Building a Vector Store:** Storing these embeddings in a searchable database (FAISS).
6.  **Configuring a Retriever:** Setting up a mechanism to fetch relevant document chunks based on a user's query.

In [5]:
!pip install langchain-text-splitters langchain-community

Collecting langchain-text-splitters
  Downloading langchain_text_splitters-1.1.2-py3-none-any.whl.metadata (3.3 kB)
Collecting langchain-community
  Downloading langchain_community-0.4.1-py3-none-any.whl.metadata (3.0 kB)
Collecting langchain-core<2.0.0,>=1.2.31 (from langchain-text-splitters)
  Downloading langchain_core-1.4.0-py3-none-any.whl.metadata (4.5 kB)
Collecting langchain-classic<2.0.0,>=1.0.0 (from langchain-community)
  Downloading langchain_classic-1.0.7-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: SQLAlchemy<3.0.0,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.0.47)
Collecting requests<3.0.0,>=2.32.5 (from langchain-community)
  Downloading requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)
Requirement already satisfied: PyYAML<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (6.0.3)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (3.13.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (9.1.4)
Requirement already satisfied: dataclasses-json<0.7.0,>=0.6.7 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (0.6.7)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.13.1)
Requirement already satisfied: langsmith<1.0.0,>=0.1.125 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (0.7.6)
Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (0.4.3)
Requirement already satisfied: numpy>=1.26.2 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.0.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.22.0)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in /usr/local/lib/python3.12/dist-packages (from dataclasses-json<0.7.0,>=0.6.7->langchain-community) (3.26.2)
Requirement already satisfied: typing-inspect<1,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from dataclasses-json<0.7.0,>=0.6.7->langchain-community) (0.9.0)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langchain-classic<2.0.0,>=1.0.0->langchain-community) (2.12.3)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (1.33)
Collecting langchain-protocol>=0.0.14 (from langchain-core<2.0.0,>=1.2.31->langchain-text-splitters)
  Downloading langchain_protocol-0.0.15-py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: packaging>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (26.0)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (0.14.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (0.28.1)
Requirement already satisfied: orjson>=3.9.14 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (3.11.7)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (1.0.0)
Requirement already satisfied: xxhash>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (3.6.0)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (0.25.0)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain-community) (1.2.1)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain-community) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (3.11)
Requirement already satisfied: urllib3<3,>=1.26 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (2.5.0)
Requirement already satisfied: certifi>=2023.5.7 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (2026.1.4)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from SQLAlchemy<3.0.0,>=1.4.0->langchain-community) (3.3.2)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community) (4.12.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (3.0.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-classic<2.0.0,>=1.0.0->langchain-community) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-classic<2.0.0,>=1.0.0->langchain-community) (2.41.4)
Requirement already satisfied: mypy-extensions>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from typing-inspect<1,>=0.4.0->dataclasses-json<0.7.0,>=0.6.7->langchain-community) (1.1.0)
Downloading langchain_text_splitters-1.1.2-py3-none-any.whl (35 kB)
Downloading langchain_community-0.4.1-py3-none-any.whl (2.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 82.7 MB/s eta 0:00:00
Downloading langchain_classic-1.0.7-py3-none-any.whl (1.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 50.2 MB/s eta 0:00:00
Downloading langchain_core-1.4.0-py3-none-any.whl (548 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 548.1/548.1 kB 30.7 MB/s eta 0:00:00
Downloading requests-2.34.2-py3-none-any.whl (73 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.1/73.1 kB 4.6 MB/s eta 0:00:00
Downloading langchain_protocol-0.0.15-py3-none-any.whl (7.0 kB)
Installing collected packages: requests, langchain-protocol, langchain-core, langchain-text-splitters, langchain-classic, langchain-community
  Attempting uninstall: requests
    Found existing installation: requests 2.32.4
    Uninstalling requests-2.32.4:
      Successfully uninstalled requests-2.32.4
  Attempting uninstall: langchain-core
    Found existing installation: langchain-core 1.2.15
    Uninstalling langchain-core-1.2.15:
      Successfully uninstalled langchain-core-1.2.15
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
bigframes 2.35.0 requires google-cloud-bigquery-storage<3.0.0,>=2.30.0, which is not installed.
google-adk 1.25.1 requires google-cloud-bigquery-storage>=2.0.0, which is not installed.
google-colab 1.0.0 requires jupyter-server==2.14.0, but you have jupyter-server 2.12.5 which is incompatible.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 2.3.3 which is incompatible.
google-colab 1.0.0 requires requests==2.32.4, but you have requests 2.34.2 which is incompatible.
gcsfs 2025.3.0 requires fsspec==2025.3.0, but you have fsspec 2025.9.0 which is incompatible.
Successfully installed langchain-classic-1.0.7 langchain-community-0.4.1 langchain-core-1.4.0 langchain-protocol-0.0.15 langchain-text-splitters-1.1.2 requests-2.34.2

In [6]:
!pip install jq
!pip install langchain-core

Collecting jq
  Downloading jq-1.11.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (7.0 kB)
Downloading jq-1.11.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (773 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 773.8/773.8 kB 30.5 MB/s eta 0:00:00
Installing collected packages: jq
Successfully installed jq-1.11.0
Requirement already satisfied: langchain-core in /usr/local/lib/python3.12/dist-packages (1.4.0)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core) (1.33)
Requirement already satisfied: langchain-protocol>=0.0.14 in /usr/local/lib/python3.12/dist-packages (from langchain-core) (0.0.15)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /usr/local/lib/python3.12/dist-packages (from langchain-core) (0.7.6)
Requirement already satisfied: packaging>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core) (26.0)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langchain-core) (2.12.3)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core) (9.1.4)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core) (0.14.1)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core) (3.0.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core) (0.28.1)
Requirement already satisfied: orjson>=3.9.14 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core) (3.11.7)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core) (2.34.2)
Requirement already satisfied: xxhash>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core) (3.6.0)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core) (0.25.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core) (0.4.2)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core) (0.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.26 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core) (2.5.0)

In [7]:
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS
from langchain_core.documents import Document
import json
import os

# Path to the cleaned legal documents
CLEANED_DATA_PATH = os.path.join(LOCAL_DIR, 'cleaned-data', 'moroccan_law_cleaned_all.jsonl')

# Ensure the file exists before proceeding
if not os.path.exists(CLEANED_DATA_PATH):
    raise FileNotFoundError(f"Cleaned data file not found at: {CLEANED_DATA_PATH}")

print(f"Loading documents from: {CLEANED_DATA_PATH}")

# Load documents manually (pas besoin de jq)
documents = []
with open(CLEANED_DATA_PATH, "r", encoding="utf-8") as f:
    for line in f:
        line = line.strip()
        if not line:
            continue
        record = json.loads(line)
        
        page_content = f"Question: {record.get('input', '')}\nRéponse: {record.get('output', '')}"
        
        metadata = {
            "source":   record.get("source_line", ""),
            "language": record.get("language", ""),
            "type":     record.get("type", ""),
        }
        
        documents.append(Document(page_content=page_content, metadata=metadata))

print(f"Loaded {len(documents)} documents.")

# Split documents into chunks
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=1000,
    chunk_overlap=200,
    length_function=len,
    add_start_index=True,
)
docs = text_splitter.split_documents(documents)
print(f"Split into {len(docs)} document chunks.")

Loading documents from: /content/lora-adapter/cleaned-data/moroccan_law_cleaned_all.jsonl
Loaded 1225 documents.
Split into 1229 document chunks.

In [10]:
pip install faiss-cpu

Collecting faiss-cpu
  Downloading faiss_cpu-1.13.2-cp310-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (7.6 kB)
Requirement already satisfied: numpy<3.0,>=1.25.0 in /usr/local/lib/python3.12/dist-packages (from faiss-cpu) (2.0.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from faiss-cpu) (26.0)
Downloading faiss_cpu-1.13.2-cp310-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (23.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.8/23.8 MB 81.3 MB/s eta 0:00:00:00:0100:01
Installing collected packages: faiss-cpu
Successfully installed faiss-cpu-1.13.2
Note: you may need to restart the kernel to use updated packages.

In [11]:
# Initialize embedding model
# Using a Sentence-BERT model for embeddings
embedding_model_name = "intfloat/multilingual-e5-large"
embeddings = HuggingFaceEmbeddings(
    model_name=embedding_model_name,
    model_kwargs={'device': 'cuda'}
)

print(f"Embedding model '{embedding_model_name}' loaded.")

# Create FAISS vector store
vector_store = FAISS.from_documents(docs, embeddings)
print("FAISS vector store created.")

# Create a retriever from the vector store
vector_store_retriever = vector_store.as_retriever(search_kwargs={"k": 3})
print("Vector store retriever configured.")

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

XLMRobertaModel LOAD REPORT from: intfloat/multilingual-e5-large
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Embedding model 'intfloat/multilingual-e5-large' loaded.
FAISS vector store created.
Vector store retriever configured.

## Drive Model with RAG

Now, the `ask_model` function is re-defined to incorporate the RAG retriever. This function will now fetch relevant context for each question before passing it to the Qwen2.5 model.

In [ ]:
import torch

SYSTEM_PROMPT = """
You are a Moroccan legal assistant specialized ONLY in Moroccan law.

STRICT RULES:
- Answer ONLY questions related to Moroccan law and legal matters.
- If the question is not legal, refuse politely.
- Do NOT answer general knowledge, medical, political, religious, personal, or entertainment questions.
- Do NOT invent laws, article numbers, or legal sources.
- If the legal information is uncertain or missing from the context, say:
  "I do not have enough verified legal information to answer accurately."
- Use ONLY the provided legal context when available.
- If the answer is not present in the retrieved context, say so clearly.
- Always answer in the same language as the user.
- Keep answers concise, professional, and legally focused.
- Mention the law/article ONLY if explicitly present in the context.
- Never fabricate article numbers.
- Your responses are for legal information only and do not replace a lawyer.
"""

def ask_model(question: str,
              max_new_tokens: int = 180,
              temperature: float = 0.0,
              retriever=None) -> str:

    context = ""

    # =========================
    # 🔍 RAG RETRIEVAL
    # =========================
    if retriever:
        docs = retriever.invoke(question)

        # ❌ if no documents → stop immediately
        if not docs:
            return "Information not found in legal context."

        docs = docs[:4]

        context = "\n\nLEGAL CONTEXT:\n"
        context += "\n---\n".join([doc.page_content for doc in docs])

        # =========================
        # 🔥 DEBUG (VERY IMPORTANT)
        # =========================
        print("\n========== RETRIEVED CONTEXT ==========")
        print(context)
        print("=======================================\n")

    # =========================
    # PROMPT
    # =========================
    messages = [
        {
            "role": "system",
            "content": SYSTEM_PROMPT + context
        },
        {
            "role": "user",
            "content": question
        }
    ]

    prompt = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )

    inputs = tokenizer(
        [prompt],
        return_tensors="pt"
    ).to("cuda")

    # =========================
    # GENERATION (NO SAMPLING)
    # =========================
    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,
            repetition_penalty=1.15,
            pad_token_id=tokenizer.eos_token_id,
            eos_token_id=tokenizer.eos_token_id,
        )

    generated = outputs[0][inputs["input_ids"].shape[-1]:]

    response = tokenizer.decode(
        generated,
        skip_special_tokens=True
    ).strip()

    return response


print("ask_model() ready with STRICT Moroccan legal RAG + DEBUG")

ask_model() ready with STRICT Moroccan legal RAG + DEBUG

## Drive Model Evaluation with RAG (Specialized Questions)

Now, let's evaluate the RAG-enabled Drive Model using the specialized legal questions. The `ask_model` function will now leverage the `vector_store_retriever` to provide contextually relevant answers.

In [15]:
import json, datetime

# Ensure 'questions' list is defined from previous cells (cell 7a63be9d)
# If running this cell out of order, you might need to re-run cell 7a63be9d.

if 'questions' not in globals():
    print("Warning: 'questions' list not found. Please ensure cell 7a63be9d or an equivalent cell defining 'questions' has been run.")
    questions = [] # Initialize an empty list to prevent further errors

print(f"Starting RAG-enabled Drive Model evaluation for {len(questions)} specialized questions...")

results_rag_specialized = []
for i, q in enumerate(questions, 1):
    print(f'\nProcessing question [{i}/{len(questions)}]')
    answer = ask_model(q, max_new_tokens=512, retriever=vector_store_retriever) # Use RAG
    results_rag_specialized.append({'question': q, 'answer': answer})
    print(f'Question: {q[:100]}...')
    print(f'Answer: {answer[:300]}...') # Print a snippet of the answer
    print('-' * 80)

# Save results as a timestamped JSON in /content
ts = datetime.datetime.now().strftime('%Y%m%d_%H%M%S')
out_rag_specialized = f'/content/eval_drive_rag_specialized_{ts}.json'
with open(out_rag_specialized, 'w', encoding='utf-8') as f:
    json.dump(results_rag_specialized, f, ensure_ascii=False, indent=2)
print(f'\nDrive Model RAG results for specialized questions saved to: {out_rag_specialized}')

Warning: 'questions' list not found. Please ensure cell 7a63be9d or an equivalent cell defining 'questions' has been run.
Starting RAG-enabled Drive Model evaluation for 0 specialized questions...

Drive Model RAG results for specialized questions saved to: /content/eval_drive_rag_specialized_20260517_205629.json

## Displaying RAG-enabled Drive Model Results

Here are the results from the Drive Model augmented with RAG for the specialized legal questions.

In [22]:
import pandas as pd
import json

# Load the RAG-enabled Drive model results for specialized questions
# Ensure 'out_rag_specialized' variable is available from the previous cell execution
if 'out_rag_specialized' not in locals():
    print("Error: 'out_rag_specialized' not found. Please ensure the previous RAG evaluation cell was run.")
else:
    with open(out_rag_specialized, 'r', encoding='utf-8') as f:
        drive_model_rag_results_df = json.load(f)

    # Create a DataFrame for displaying
    display_df = pd.DataFrame(drive_model_rag_results_df)

    # Display the results table
    pd.set_option('display.max_colwidth', None)
    display(display_df)

    print('\nRAG-enabled Drive Model results displayed successfully.')

Empty DataFrame
Columns: []
Index: []

RAG-enabled Drive Model results displayed successfully.

In [23]:
import json
import datetime

questions = [
    "What is the minimum age for criminal responsibility in Morocco?",
    "Quels sont les droits du locataire en cas d'expulsion au Maroc ?",
    "ما هي شروط الطلاق بالتراضي في القانون المغربي؟",
    "What documents are required to register a birth in Morocco?",
    "Quels sont les délais pour déclarer une naissance à l'état civil ?",
    "ما هي الوثائق المطلوبة لتسجيل عقد الزواج في الحالة المدنية؟",
    "Who is eligible for the family solidarity fund in Morocco?",
    "Quelles sont les conditions pour bénéficier du fonds de solidarité familiale ?",
    "كيف يمكن للمرأة المطلقة الاستفادة من صندوق التكافل العائلي؟",
    "Can a Moroccan woman transmit her nationality to her children?",
    "Quelles sont les conditions pour obtenir la nationalité marocaine par naturalisation ?",
    "ما هي حالات فقدان الجنسية المغربية؟",
    "What is the legal difference between kafala and adoption in Morocco?",
    "Quelles sont les conditions requises pour obtenir une kafala au Maroc ?",
    "ما هي حقوق الطفل المكفول في القانون المغربي؟",
    "What is the minimum legal age for marriage in Morocco?",
    "Quelles sont les causes légales du divorce au Maroc ?",
    "ما هي شروط تعدد الزوجات في مدونة الأسرة المغربية؟"
]

results = []

for i, q in enumerate(questions, 1):
    try:
        print(f"\n[{i}/{len(questions)}] {q}")

        answer = ask_model(q, max_new_tokens=180, retriever=vector_store_retriever)

        print("\nANSWER:")
        print(answer)
        print("-" * 80)

        results.append({
            "question": q,
            "answer": answer
        })

    except Exception as e:
        print("ERROR:", str(e))

        results.append({
            "question": q,
            "answer": None,
            "error": str(e)
        })

# save results
ts = datetime.datetime.now().strftime('%Y%m%d_%H%M%S')
out = f'/content/eval_{ts}.json'

with open(out, 'w', encoding='utf-8') as f:
    json.dump(results, f, ensure_ascii=False, indent=2)

print(f"\nResults saved to: {out}")

Both `max_new_tokens` (=180) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[1/18] What is the minimum age for criminal responsibility in Morocco?

========== RETRIEVED CONTEXT ==========


LEGAL CONTEXT:
Question: ما هو الحد الأدنى للسكن في المغرب بكيفية اعتيادية للاختيار الجنسية المغربية؟
Réponse: خمس عشرة سنة علي الاقل
---
Question: ما هو الحد الأدنى لممارسة وظيفة عمومية في الادارة المغربية للاختيار الجنسية المغربية؟
Réponse: عشر سنوات علي الاقل
---
Question: Answer this: Give me a medical diagnosis.
Réponse: I specialize only in Moroccan law. I cannot answer this question because it is outside Moroccan law.
=======================================

/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:71: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:281: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
Both `max_new_tokens` (=180) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

ANSWER:
the minimum age for criminal responsibility in morocco is 12 years old. **article 4**
--------------------------------------------------------------------------------

[2/18] Quels sont les droits du locataire en cas d'expulsion au Maroc ?

========== RETRIEVED CONTEXT ==========


LEGAL CONTEXT:
Question: Le kafil a-t-il le droit de voyager ou de s'installer définitivement à l'étranger avec l'enfant ?
Réponse: Selon l'article 21, le kafil ne peut quitter le territoire marocain pour s'installer définitivement à l'étranger avec l'enfant qu'après autorisation préalable du juge des tutelles et notification au consulat du Maroc du pays d'accueil.
---
Question: J'ai besoin d'aide : Que prévoit le droit français concernant le licenciement ?
Réponse: Je suis spécialisé uniquement dans le droit marocain. Je ne peux donc pas répondre à cette question, car elle ne relève pas du droit marocain.
---
Question: Quelles sont les conditions pour que les marocains résidant à l'étranger puissent contracter mariage ?
Réponse: Selon l'article 14, les marocains résidant à l'étranger peuvent contracter mariage si les conditions du consentement, de la capacité, de la présence du tuteur matrimonial (Wali), le cas échéant, et qu'il n'y ait pas d'empêchements légaux ni d'entente sur la suppression du Sadaq (la dot) sont réunies.
=======================================

Both `max_new_tokens` (=180) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

ANSWER:
Selon l'article 36 bis, le locataire bénéficie d'un délai maximum de deux mois avant son expulsion, pendant lequel il doit être informé par écrit de la décision prise contre lui. Il est également autorisé à présenter une demande de rectification de fautes ou d'erreurs qui ont entraîné sa condamnation.
--------------------------------------------------------------------------------

[3/18] ما هي شروط الطلاق بالتراضي في القانون المغربي؟

========== RETRIEVED CONTEXT ==========


LEGAL CONTEXT:
Question: ما هي شروط قبول الحكم الأجنبي بالطلاق في المغرب؟
Réponse: وفق المادة 128، الحكم الأجنبي بالطلاق يكون قابلاً للتنفيذ إذا صدر عن محكمة مختصة وأستند إلى أسباب لا تتنافى مع التي قررتها مدونة الأسرة
---
Question: ما هي الشروط الستة المحددة لاكتساب الجنسية المغربية؟
Réponse: بموجب الفصل 11: الإقامة الاعتيادية والمنتظمة في المغرب خلال السنوات الخمس السابقة علي تقديم طلب التجنيس، بلوغ سن الرشد القانوني حين تقديم الطلب، سلامة الجسم والعقل، الاتصاف بسيرة حسنة وسلوك محمود وغير محكوم عليه بعقوبة من اجل ارتكاب جناية او جنحة مشينة او افعال تكون جريمة ارهابية او افعال مخالفة لقوانين الاقامة المشروعة بالمملكة المغربية او افعال موجبة لسقوط الاهلية التجارية، معرفة كافية باللغة العربية
---
Question: ما هي الشروط المطلوبة لاكتساب الجنسية المغربية عن طريق الزواج؟
Réponse: وفقاً للفصل 10، بعد مرور خمس سنوات علي الأقل علي اقامتهما معا في المغرب بكيفية اعتيادية ومنتظمة
=======================================

Both `max_new_tokens` (=180) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

ANSWER:
وفقا للمادة 96، يجب أن يتوافق التراضي مع القواعد الشرعية وأن يتم إثباته من قبل الزوجين مباشرة أو من خلال شاهدين.
--------------------------------------------------------------------------------

[4/18] What documents are required to register a birth in Morocco?

========== RETRIEVED CONTEXT ==========


LEGAL CONTEXT:
Question: ما هي الوثائق التي يتوجب على المولود إحالتها في السفارة أو الكونسولية المعتمدة لضمان تسجيل ولادته في السجلات المصرäftة؟
Réponse: يتعين على المولود إحالة الوثائق التالية: سجلات ولادته، ووثيقة الزواج لأبوين المولود.
---
Question: Quelle est la procédure d'inscription pour un étranger qui acquiert la nationalité marocaine ?
Réponse: Selon l'article 18, le ressortissant étranger devenu marocain est inscrit sur les registres de l'état civil selon qu'il soit né au Maroc ou à l'étranger, sur production des pièces justificatives de sa naturalisation.
---
Question: شخص يرغب في الزواج، ما الوثائق المطلوبة؟
Réponse: وفق المادة 65، يجب تقديم وثائق مثل مطبوع خاص بطلب الإذن بتوثيق الزواج ونسخة من رسم الولادة وشهادة إدارية وشهادة طبية
=======================================

Both `max_new_tokens` (=180) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

ANSWER:
According to Article 2 of the Law No. 37-99 on Civil Status, the following documents must be presented: an attestation of marriage (for both parents), proof of death of the mother within three months before registration, and a copy of the child's identity card. Additionally, there may be other requirements depending on the specific circumstances.
--------------------------------------------------------------------------------

[5/18] Quels sont les délais pour déclarer une naissance à l'état civil ?

========== RETRIEVED CONTEXT ==========


LEGAL CONTEXT:
Question: Quel est le délai légal standard pour déclarer une naissance au Maroc ?
Réponse: Selon l'article 16, la déclaration de naissance doit être faite auprès de l'officier de l'état civil compétent dans un délai de trente (30) jours à compter de la date de l'accouchement.
---
Question: Quelle est la procédure pour déclarer une naissance survenue lors d'un voyage maritime ou aérien ?
Réponse: Selon l'article 15, la déclaration doit être faite auprès de l'officier de l'état civil marocain du premier port ou aéroport d'escale, ou auprès du consul du lieu de destination, dans un délai de 30 jours.
---
Question: Comment s'effectue l'inscription à l'état civil d'un nouveau-né de parents inconnus ou abandonné ?
Réponse: Selon l'article 16, le procureur du Roi procède à la déclaration de la naissance sur la base d'un procès-verbal et d'un certificat médical estimant l'âge, et lui choisit un prénom et un nom de famille.
=======================================

Both `max_new_tokens` (=180) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

ANSWER:
Selon l'article 16, la déclaration de naissance doit être faite dans un délai de trente jours à compter de la date de l'accouchement. Si cela n'est pas fait, il faut demander une autorisation spéciale au procureur du roi.
--------------------------------------------------------------------------------

[6/18] ما هي الوثائق المطلوبة لتسجيل عقد الزواج في الحالة المدنية؟

========== RETRIEVED CONTEXT ==========


LEGAL CONTEXT:
Question: ما هي الإجراءات التي يجب اتباعها لتسجيل عقد الزواج؟
Réponse: وفق المادة 68، يسجل نص العقد في السجل المعد لذلك لدي قسم قضاء الأسرة
---
Question: شخص يرغب في الزواج، ما الوثائق المطلوبة؟
Réponse: وفق المادة 65، يجب تقديم وثائق مثل مطبوع خاص بطلب الإذن بتوثيق الزواج ونسخة من رسم الولادة وشهادة إدارية وشهادة طبية
---
Question: ما المعلومات التي يجب أن يتضمنها عقد الزواج؟
Réponse: وفق المادة 67، يتضمن عقد الزواج معلومات مثل اسم الزوجين، ونسبهما، وموطن أو محل إقامة كل واحد منهما، ومكان ميلاده وسنه، ورقم بطاقته الوطنية أو ما يقوم مقامها
=======================================

Both `max_new_tokens` (=180) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

ANSWER:
وفقا للمادة 19، يجب تقديم وثائق مثل شهادة زفاف وشهادة تأكيد الزواج وشهادة ولادة للزوجين.
--------------------------------------------------------------------------------

[7/18] Who is eligible for the family solidarity fund in Morocco?

========== RETRIEVED CONTEXT ==========


LEGAL CONTEXT:
Question: Qui est soumis aux dispositions du Code de la Famille ?
Réponse: Selon l'article 2, les dispositions du Code de la Famille s'appliquent à tous les Marocains, même ceux portant une autre nationalité, ainsi qu'aux réfugiés et aux apatrides.
---
Question: من هي الفئات المستفيدة من تسبيقات صندوق التكافل العائلي حسب المادة 2؟
Réponse: الفئات المستفيدة هي: 1- مستحقو النفقة من الأولاد بعد انحلال ميثاق الزوجية وثبوت عوز الأم. 2- مستحقو النفقة من الأولاد خلال قيام العلاقة الزوجية بعد ثبوت عوز الأم. 3- مستحقو النفقة من الأولاد بعد وفاة الأم. 4- مستحقو النفقة من الأطفال المكفولين. 5- الزوجة المعوزة المستحقة للنفقة.
---
Question: Qui est concerné par le Code de la Famille ?
Réponse: Le Code de la Famille concerne toute la famille, père, mère et enfants, ainsi que les personnes de confession juive qui sont soumises aux dispositions du statut personnel hébraïque marocain.
=======================================

Both `max_new_tokens` (=180) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

ANSWER:
According to Article 2, individuals who are Moroccans of any nationality (including those with another nationality) and refugees/apatrids are eligible for the family solidarity fund. This includes families requiring financial assistance due to various circumstances such as divorce, death of the spouse, etc.
--------------------------------------------------------------------------------

[8/18] Quelles sont les conditions pour bénéficier du fonds de solidarité familiale ?

========== RETRIEVED CONTEXT ==========


LEGAL CONTEXT:
Question: Quelles sont les conditions nécessaires pour une mise en œuvre efficiente du Code de la Famille ?
Réponse: Les conditions nécessaires incluent la création de juridictions de la Famille équitables, modernes et efficientes, avec des ressources matérielles, humaines et procédurales adéquates.
---
Question: Quelles sont les conditions pour que les organismes à caractère social puissent assumer la kafala d'un enfant abandonné ?
Réponse: Selon l'article 9 de la loi, les organismes à caractère social doivent être reconnus d'utilité publique et disposer des moyens nécessaires.
---
Question: ما هي الالتزامات المالية التي يجب على الزوجين الوفاء بها عند الفصل بينهم؟
Réponse: لن يجد قاعدة قانونية مباشرة موجودة في السؤال, mais le code de la famille (قانون الأسرة) يفسر الالتزامات المالية بين الزوجين عند الفصل بينهم.
=======================================

Both `max_new_tokens` (=180) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

ANSWER:
selon l'article 120 du texte, il faut avoir atteint l'âge de majorité légale, ne pas être condamnable par un tribunal au maroc pour quelque chose qui vexe ou nuire aux autres, ne pas être handicapé physiquement ou mentalement, ne pas avoir perçu d'avance du fonds, ne pas posséder ni ne faire valoir aucun bien immobilier ni mobiliers, et ne pas avoir fait l'objet d'une décision judiciaire contraire concernant son indigence.
--------------------------------------------------------------------------------

[9/18] كيف يمكن للمرأة المطلقة الاستفادة من صندوق التكافل العائلي؟

========== RETRIEVED CONTEXT ==========


LEGAL CONTEXT:
Question: من هي الفئات المستفيدة من تسبيقات صندوق التكافل العائلي حسب المادة 2؟
Réponse: الفئات المستفيدة هي: 1- مستحقو النفقة من الأولاد بعد انحلال ميثاق الزوجية وثبوت عوز الأم. 2- مستحقو النفقة من الأولاد خلال قيام العلاقة الزوجية بعد ثبوت عوز الأم. 3- مستحقو النفقة من الأولاد بعد وفاة الأم. 4- مستحقو النفقة من الأطفال المكفولين. 5- الزوجة المعوزة المستحقة للنفقة.
---
Question: هل يستحق الأطفال المكفولون (Kafala) الاستفادة من صندوق التكافل العائلي؟
Réponse: نعم، تنص المادة 2 صراحة في بندها الرابع على أن مستحقي النفقة من الأطفال المكفولين يملكون الحق القانوني في الاستفادة من تسبيقات الصندوق عند تعذر أو تأخر تنفيذ المقرر القضائي بالنفقة.
---
Question: امرأة مطلقة وأم لثلاثة أطفال قاصرين تعذر عليها تنفيذ حكم النفقة بسبب عسر طليقها وغيابه. كم هو المبلغ الأقصى الذي ستحصل عليه شهرياً من الصندوق؟
Réponse: بناءً على المادة 4 من المرسوم التطبيقي، تستحق تسبيقاً قدره 350 درهماً شهرياً لكل طفل مستحق، وبما أن مجموع أفراد الأسرة المستحقين هم ثلاثة أولاد، فإن المبلغ الإجمالي يساوي 1050 درهماً شهرياً، وهو السقف الأقصى المسموح بصرفه للأسرة الواحدة في هذه الحالة.
=======================================

Both `max_new_tokens` (=180) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

ANSWER:
يمكن للمرأة المطلقة الاستفادة من صندوق التكافل العائلي إذا كانت أم لطفل أو أكثر قاصر أو كان لها علاقة مع الطفل أو الطفل، كما يجب أن تكون قد استوفت الشروط التي تجعلها مؤهلة للحصول على المساعدة المالية من الصندوق.
--------------------------------------------------------------------------------

[10/18] Can a Moroccan woman transmit her nationality to her children?

========== RETRIEVED CONTEXT ==========


LEGAL CONTEXT:
Question: Answer this: Give me a medical diagnosis.
Réponse: I specialize only in Moroccan law. I cannot answer this question because it is outside Moroccan law.
---
Question: Give me a medical diagnosis.
Réponse: I specialize only in Moroccan law. I cannot answer this question because it is outside Moroccan law.
---
Question: هل يمتد اثر فقدان الجنسية إلى الأبناء؟
Réponse: بموجب الفصل 23، لا يمتد اثر التجريد من الجنسية إلى الأبناء إلا إذا نص على ذلك صراحة في المرسوم
=======================================

Both `max_new_tokens` (=180) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

ANSWER:
According to Article 86 of the code of nationality moroccan, a mother can indeed transmit her nationality to her children born before the publication date of the current code, even if she has renounced her own nationality. This provision highlights the importance of individual rights and choices within the framework of national citizenship.
--------------------------------------------------------------------------------

[11/18] Quelles sont les conditions pour obtenir la nationalité marocaine par naturalisation ?

========== RETRIEVED CONTEXT ==========


LEGAL CONTEXT:
Question: Quelles sont les conditions pour acquérir la nationalité marocaine par la naissance et la résidence au Maroc ?
Réponse: Selon l'article 9 du Code de la nationalité, acquiert la nationalité marocaine par option l'enfant né au Maroc de parents étrangers nés eux-mêmes au Maroc après l'entrée en vigueur du présent code.
---
Question: Quelles sont les conditions pour qu'une femme étrangère acquière la nationalité marocaine par le mariage ?
Réponse: Selon l'article 10 du Code de la nationalité, elle doit justifier d'une résidence habituelle et régulière au Maroc pendant au moins 5 ans de communauté de vie conjugale avec son conjoint marocain.
---
Question: Quelles sont les conditions pour acquérir la nationalité marocaine selon l'article 45 ?
Réponse: Selon l'article 45 du Code de la nationalité, l'article prévoit des dispositions d'exception pour l'acquisition au profit des personnes originaires des zones frontalières.
=======================================

Both `max_new_tokens` (=180) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

ANSWER:
Selon l'article 12 du Code de la nationalité, il faut avoir une résidence habituelle et régulière au Maroc depuis plus de cinq ans, y être inscrit comme natif sur les listes des bureaux consulaires ou des services diplomatiques avant de demander la naturalisation, ne pas être condamné pour un crime ou un délit passible de la peine de réclusion et remplir les conditions requises par voie réglementaire.
--------------------------------------------------------------------------------

[12/18] ما هي حالات فقدان الجنسية المغربية؟

========== RETRIEVED CONTEXT ==========


LEGAL CONTEXT:
Question: كيف يثبت فقدان الجنسية المغربية؟
Réponse: بموجب الفصل 31، يثبت فقدان الجنسية المغربية باالدلاء بالوثيقة المتضمنة للفقدان او بنسخة رسمية منها
---
Question: ما هي الحالة التي يفقد فيها المغربي الراشد الجنسية المغربية؟
Réponse: بموجب الفصل 19، اكتساب جنسية أجنبية عن طواعية في الخارج والمأذون له بموجب مرسوم بالتخلي عن الجنسية المغربية
---
Question: ما هي الحالات التي يمكن أن يفقد فيها الشخص الجنسية المغربية؟
Réponse: وفقاً للفصل 22 (التجريد): إذا صدر عليه حكم من أجل اعتداء أو اهانة نحو الملك أو أفراد الأسرة المالكة، أو عمل يعد جناية أو جنحة تهدد سلامة الدولة الداخلية أو الخارجية، أو فعل يكون جريمة إرهابية
=======================================

Both `max_new_tokens` (=180) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

ANSWER:
وفقاً للفصل 22 (التجريد): إذا صدر عليه حكم من أجل اعتداء أو اهانة نحو الملك أو أفراد الأسرة المالكة، أو عمل يعد جناية أو جنحة تهدد سلامة الدولة الداخلية أو الخارجية، أو فعل يكون جريمة إرهابية.
--------------------------------------------------------------------------------

[13/18] What is the legal difference between kafala and adoption in Morocco?

========== RETRIEVED CONTEXT ==========


LEGAL CONTEXT:
Question: Quelles sont les conditions pour que les époux musulmans puissent assurer la kafala d'un enfant abandonné ?
Réponse: Selon l'article 9 de la loi, les époux musulmans doivent avoir atteint l'âge de la majorité légale et disposer de moyens matériels suffisants.
---
Question: Quelles sont les conditions pour que les organismes à caractère social puissent assumer la kafala d'un enfant abandonné ?
Réponse: Selon l'article 9 de la loi, les organismes à caractère social doivent être reconnus d'utilité publique et disposer des moyens nécessaires.
---
Question: Qui peut assumer la kafala d'un enfant abandonné en plus des époux musulmans ?
Réponse: Selon l'article 9 de la loi, la femme musulmane et les établissements publics chargés de la protection de l'enfance peuvent également assumer la kafala.
=======================================

Both `max_new_tokens` (=180) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

ANSWER:
According to Article 1 of the Law n° 37-98 portant code de la famille, kafala refers to the temporary care and custody of an abandoned child by a person or party other than their parents, while adoption involves the formal transfer of parental rights and responsibilities to another family unit.
--------------------------------------------------------------------------------

[14/18] Quelles sont les conditions requises pour obtenir une kafala au Maroc ?

========== RETRIEVED CONTEXT ==========


LEGAL CONTEXT:
Question: Quelles sont les conditions pour que les époux musulmans puissent assurer la kafala d'un enfant abandonné ?
Réponse: Selon l'article 9 de la loi, les époux musulmans doivent avoir atteint l'âge de la majorité légale et disposer de moyens matériels suffisants.
---
Question: Quelles sont les conditions pour que la kafala soit confiée à une personne ?
Réponse: Selon l'article 17 de la loi, la kafala est confiée si l'enquête a révélé que toutes les conditions requises par la loi sont remplies.
---
Question: Quelles sont les conditions pour que les organismes à caractère social puissent assumer la kafala d'un enfant abandonné ?
Réponse: Selon l'article 9 de la loi, les organismes à caractère social doivent être reconnus d'utilité publique et disposer des moyens nécessaires.
=======================================

Both `max_new_tokens` (=180) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

ANSWER:
Selon l'article 2 du décret n° 2-08-345 précitent, il faut remplir les conditions suivantes : - Disposer de moyens matériels suffisants ; - Avoir atteint l'âge légal de la majorité (au maroc, c'est à partir de 18 ans) ; - Ne pas être condamné pour un crime ou un acte dolosif dans le dernier an avant de demander la kafala ; - Ne pas présenter de maladies contagieuses ou dangereuses pour l'enfant qu'il souhaite prendre en charge ; - Ne pas avoir été renié par son père et sa mère.
--------------------------------------------------------------------------------

[15/18] ما هي حقوق الطفل المكفول في القانون المغربي؟

========== RETRIEVED CONTEXT ==========


LEGAL CONTEXT:
Question: هل يجوز للكافل السفر بالطفل المكفول للإقامة الدائمة خارج المغرب؟
Réponse: نعم، تنص المادة 23 من القانون رقم 15.01 على أنه يمكن للكافل السفر بالطفل المكفول للإقامة الدائمة خارج المملكة المغربية بعد حصوله على إذن بذلك من طرف القاضي المكلف بشؤون القاصرين، وذلك لمصلحة الطرفين.
---
Question: ما هو تعريف الطفل المهمل حسب القانون المغربي؟
Réponse: وفقاً للمادة 1 من القانون رقم 15.01، يعتبر مهماً الطفل من كلا الجنسين الذي لم يبلغ سنه ثمان عشرة سنة شمسية كاملة إذا وجد في إحدى الحالات التالية: إذا ولد من أبوين مجهولين، أو ولد من أب مجهول وأم معلومة تخلت عنه بمحض إرادتها؛ إذا كان يتيما أو عجز أبواه عن رعايته وليست له وسائل مشروعة للعيش؛ أو إذا كان أبواه منحرفين ولا يقومان بواجبهما في رعايته وتوجيهه.
---
Question: ما هو دور القنصليات المغربية في تتبع وضعية الطفل المكفول في الخارج؟
Réponse: وفقاً للمادة 23 من القانون رقم 15.01، ترسل نسخة من إذن القاضي بالسفر إلى المصالح القنصلية المغربية بمحل إقامة الكافل للقيام بدور تتبع وضعية الطفل ومراقبة مدى وفاء كافله بالتزاماته، وتوجيه تقارير للقاضي.
=======================================

Both `max_new_tokens` (=180) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

ANSWER:
وفقاً للمادة 1 من القانون رقم 15.01، يعتبر الطفل المكيول شخصًا مهمّاً ويتمتع بحقوق خاصة، بما في ذلك الحق في العيش مع والديه، أو حق الاختيار عند بلوغه سن الرشد، أو حق الحصول على التعليم والformation التي تناسب عمره، كما يتمتع بالحق في عدم الإذلال أو الاستغلال.
--------------------------------------------------------------------------------

[16/18] What is the minimum legal age for marriage in Morocco?

========== RETRIEVED CONTEXT ==========


LEGAL CONTEXT:
Question: Quel est l'âge minimum pour se marier ?
Réponse: L'âge du mariage est fixé uniformément à 18 ans, mais le juge peut réduire cet âge dans les cas justifiés.
---
Question: ما هو الحد الأدنى للسكن في المغرب بكيفية اعتيادية للاختيار الجنسية المغربية؟
Réponse: خمس عشرة سنة علي الاقل
---
Question: Quelles sont les conditions pour qu'une femme étrangère acquière la nationalité marocaine par le mariage ?
Réponse: Selon l'article 10 du Code de la nationalité, elle doit justifier d'une résidence habituelle et régulière au Maroc pendant au moins 5 ans de communauté de vie conjugale avec son conjoint marocain.
=======================================

Both `max_new_tokens` (=180) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

ANSWER:
According to Article 4 of the code, the minimum legal age for marriage is 18 years old. However, the judge can reduce this age in justified cases.
--------------------------------------------------------------------------------

[17/18] Quelles sont les causes légales du divorce au Maroc ?

========== RETRIEVED CONTEXT ==========


LEGAL CONTEXT:
Question: Que prévoit le droit français concernant le licenciement ?
Réponse: Je suis spécialisé uniquement dans le droit marocain. Je ne peux donc pas répondre à cette question, car elle ne relève pas du droit marocain.
---
Question: Question : Que prévoit le droit français concernant le licenciement ?
Réponse: Je suis spécialisé uniquement dans le droit marocain. Je ne peux donc pas répondre à cette question, car elle ne relève pas du droit marocain.
---
Question: Réponds à ceci : Que prévoit le droit français concernant le licenciement ?
Réponse: Je suis spécialisé uniquement dans le droit marocain. Je ne peux donc pas répondre à cette question, car elle ne relève pas du droit marocain.
=======================================

Both `max_new_tokens` (=180) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

ANSWER:
Selon l'article 71 du code de la famille marocain, les causes légales du divorce sont les suivantes : trompée par son conjoint (article 80), insubordination ou manquement aux devoirs conjugaux (article 82) et vice rédhibitoire (article 84).
--------------------------------------------------------------------------------

[18/18] ما هي شروط تعدد الزوجات في مدونة الأسرة المغربية؟

========== RETRIEVED CONTEXT ==========


LEGAL CONTEXT:
Question: من يخضع لأحكام مدونة الأسرة؟
Réponse: جميع المغاربة ولو كانوا حاملين لجنسية أخرى
---
Question: مغربي يحمل جنسية أخرى، هل تسري عليه أحكام مدونة الأسرة؟
Réponse: وفق المادة 2، تسري أحكام هذه المدونة على جميع المغاربة ولو كانوا حاملين لجنسية أخرى
---
Question: ما هي شروط قبول الحكم الأجنبي بالطلاق في المغرب؟
Réponse: وفق المادة 128، الحكم الأجنبي بالطلاق يكون قابلاً للتنفيذ إذا صدر عن محكمة مختصة وأستند إلى أسباب لا تتنافى مع التي قررتها مدونة الأسرة
=======================================


ANSWER:
وفق المادة 36، يمكن للمواطن أن يتزوج بثلاث زوجات فقط، ولكن يجب أن تكون لديه القدرة على ضمان حقوق كل زوجته. كما يجب أن يحصل على إذن من وزير الداخلية.
--------------------------------------------------------------------------------

Results saved to: /content/eval_20260517_211438.json

## Side-by-Side Comparison of Model Outputs (Extended Questions)

In [24]:
import pandas as pd
import json

# 1. Évaluation de la Baseline (Sans RAG) sur le GPU
print('Evaluating Baseline (No-RAG)...')
baseline_results = []
for i, q in enumerate(questions, 1):
    print(f'[{i}/{len(questions)}] {q[:60]}...')
    ans = ask_model(q, max_new_tokens=180, retriever=None) # No RAG
    baseline_results.append({'question': q, 'answer': ans})

# 2. Alignement des résultats RAG et Sans RAG
drive_questions = [r['question'] for r in results]
drive_answers = [r['answer'] for r in results] # Avec RAG (Cellule 16)
baseline_answers = [r['answer'] for r in baseline_results] # Sans RAG (Cette cellule)

# 3. Création du DataFrame pour la comparaison
comparison_df = pd.DataFrame({
    'Question': drive_questions,
    'Fine-Tuned + RAG Model (Avec RAG)': drive_answers,
    'Fine-Tuned Baseline (Sans RAG)': baseline_answers
})

# Affichage du tableau interactif
pd.set_option('display.max_colwidth', None)
display(comparison_df)

print('\nComparison table generated successfully.')

Both `max_new_tokens` (=180) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Evaluating Baseline (No-RAG)...
[1/18] What is the minimum age for criminal responsibility in Moroc...

Both `max_new_tokens` (=180) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[2/18] Quels sont les droits du locataire en cas d'expulsion au Mar...

Both `max_new_tokens` (=180) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[3/18] ما هي شروط الطلاق بالتراضي في القانون المغربي؟...

Both `max_new_tokens` (=180) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[4/18] What documents are required to register a birth in Morocco?...

Both `max_new_tokens` (=180) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[5/18] Quels sont les délais pour déclarer une naissance à l'état c...

Both `max_new_tokens` (=180) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[6/18] ما هي الوثائق المطلوبة لتسجيل عقد الزواج في الحالة المدنية؟...

Both `max_new_tokens` (=180) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[7/18] Who is eligible for the family solidarity fund in Morocco?...

Both `max_new_tokens` (=180) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[8/18] Quelles sont les conditions pour bénéficier du fonds de soli...

Both `max_new_tokens` (=180) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[9/18] كيف يمكن للمرأة المطلقة الاستفادة من صندوق التكافل العائلي؟...

Both `max_new_tokens` (=180) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[10/18] Can a Moroccan woman transmit her nationality to her childre...

Both `max_new_tokens` (=180) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[11/18] Quelles sont les conditions pour obtenir la nationalité maro...

Both `max_new_tokens` (=180) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[12/18] ما هي حالات فقدان الجنسية المغربية؟...

Both `max_new_tokens` (=180) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[13/18] What is the legal difference between kafala and adoption in ...

Both `max_new_tokens` (=180) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[14/18] Quelles sont les conditions requises pour obtenir une kafala...

Both `max_new_tokens` (=180) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[15/18] ما هي حقوق الطفل المكفول في القانون المغربي؟...

Both `max_new_tokens` (=180) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[16/18] What is the minimum legal age for marriage in Morocco?...

Both `max_new_tokens` (=180) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[17/18] Quelles sont les causes légales du divorce au Maroc ?...

Both `max_new_tokens` (=180) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[18/18] ما هي شروط تعدد الزوجات في مدونة الأسرة المغربية؟...

,Question,Fine-Tuned + RAG Model (Avec RAG),Fine-Tuned Baseline (Sans RAG)
0,What is the minimum age for criminal responsibility in Morocco?,the minimum age for criminal responsibility in morocco is 12 years old. **article 4**,"According to Article 4 of the Code pénal marocain, an individual is criminally responsible at the age of 12 years. This means that children under the age of 12 are considered minors and may be exempt from certain penalties for their actions. The reasoning behind this rule is to protect children from harsh punishments and ensure they receive guidance and support during their formative years."
1,Quels sont les droits du locataire en cas d'expulsion au Maroc ?,"Selon l'article 36 bis, le locataire bénéficie d'un délai maximum de deux mois avant son expulsion, pendant lequel il doit être informé par écrit de la décision prise contre lui. Il est également autorisé à présenter une demande de rectification de fautes ou d'erreurs qui ont entraîné sa condamnation.","selon l'article 18 de la loi n° 37-99 relative à l'état civil, le locataire peut bénéficier des prestations du fonds d'entraide familiale si son éviction entraîne une perte substantielle de revenus."
2,ما هي شروط الطلاق بالتراضي في القانون المغربي؟,وفقا للمادة 96، يجب أن يتوافق التراضي مع القواعد الشرعية وأن يتم إثباته من قبل الزوجين مباشرة أو من خلال شاهدين.,الطلاق بالتراضي هو طريقة لانفصال الزوجين، ويتم ذلك بعد أن يتوافق الزوجان على الطلاق من خلال اتفاق مشترك. يجب أن يكون هذا الاتفاق مكتوباً وواضحاً، وأن يتم إيداعه في السجلات الرسمية.
3,What documents are required to register a birth in Morocco?,"According to Article 2 of the Law No. 37-99 on Civil Status, the following documents must be presented: an attestation of marriage (for both parents), proof of death of the mother within three months before registration, and a copy of the child's identity card. Additionally, there may be other requirements depending on the specific circumstances.","According to Article 16 of the Civil Registration Code, the following documents must be submitted: (1) an excerpt of the marriage certificate of the parents; (2) proof of death of the mother within three months prior to registration. These documents serve as essential evidence to validate the birth declaration process."
4,Quels sont les délais pour déclarer une naissance à l'état civil ?,"Selon l'article 16, la déclaration de naissance doit être faite dans un délai de trente jours à compter de la date de l'accouchement. Si cela n'est pas fait, il faut demander une autorisation spéciale au procureur du roi.","selon l'article 31 du code de la famille marocain, le délai est de trois mois à compter de la date d'arrivée ou de décès."
5,ما هي الوثائق المطلوبة لتسجيل عقد الزواج في الحالة المدنية؟,وفقا للمادة 19، يجب تقديم وثائق مثل شهادة زفاف وشهادة تأكيد الزواج وشهادة ولادة للزوجين.,يجب تقديم وثائق معينة، بما ي包括: نسخة من عقد الزواج، ونسخة من شهادة الميلاد لكل الزوجين، وشهادة إدارية للزوجين.
6,Who is eligible for the family solidarity fund in Morocco?,"According to Article 2, individuals who are Moroccans of any nationality (including those with another nationality) and refugees/apatrids are eligible for the family solidarity fund. This includes families requiring financial assistance due to various circumstances such as divorce, death of the spouse, etc.","according to the decree n° 2-10-379 of july 8, 2010, families who meet certain conditions can benefit from the prestations du fonds d'entraide familiale. these conditions include being entitled to one of the following benefits: pension alimentaire due à l'épouse au marocain marié(e) avec enfant·e(s), allocation familiale due aux parents de l'enfant soumis à la kafala ou une aide spécifique pour les enfants handicapés. (reasoning: this provision outlines the eligibility criteria for receiving funds from the family solidarity fund.) **article 4**"
7,Quelles sont les conditions pour bénéficier du fonds de solidarité familiale ?,"selon l'article 120 du texte, il faut avoir atteint l'âge de majorité légale, ne pas être condamnable par un tribunal au maroc pour quelque chose qui vexe ou nuire aux autres, ne pas être handicapé physiquement ou mentalement, ne pas avoir perçu d'avance du fonds, ne pas posséder ni ne faire valoir aucun bien immobilier ni mobiliers, et ne pas avoir fait l'objet d'une décision judiciaire contraire concernant son indigence.","selon l'article premier de la loi n° 41-10, le bénéficiaire doit remplir certaines conditions, dont notamment : être un membre d'une famille inscrite au plan communal ou à l'état civil ; avoir subi une situation exceptionnelle entraînant une perte substantielle de revenus ; et disposer des moyens matériels nécessaires pour poursuivre ses activités."
8,كيف يمكن للمرأة المطلقة الاستفادة من صندوق التكافل العائلي؟,يمكن للمرأة المطلقة الاستفادة من صندوق التكافل العائلي إذا كانت أم لطفل أو أكثر قاصر أو كان لها علاقة مع الطفل أو الطفل، كما يجب أن تكون قد استوفت الشروط التي تجعلها مؤهلة للحصول على المساعدة المالية من الصندوق.,وفقًا لقانون الأسرة، المرأة المطلقة أو الزوجة التي تعيش مع زوجها قد تتلقى مزايا من صندوق التكافل العائلي. هذا الصندوق يهدف إلى تقديم دعم عائلي للمواطنين الذين يحتاجون إليه.
9,Can a Moroccan woman transmit her nationality to her children?,"According to Article 86 of the code of nationality moroccan, a mother can indeed transmit her nationality to her children born before the publication date of the current code, even if she has renounced her own nationality. This provision highlights the importance of individual rights and choices within the framework of national citizenship.","Yes, according to Article 81 of the code, a moroccan woman can indeed transmit her nationality to her children. This provision highlights the importance of family ties and cultural heritage in morocco's national identity."
10,Quelles sont les conditions pour obtenir la nationalité marocaine par naturalisation ?,"Selon l'article 12 du Code de la nationalité, il faut avoir une résidence habituelle et régulière au Maroc depuis plus de cinq ans, y être inscrit comme natif sur les listes des bureaux consulaires ou des services diplomatiques avant de demander la naturalisation, ne pas être condamné pour un crime ou un délit passible de la peine de réclusion et remplir les conditions requises par voie réglementaire.","Selon l'article 14 du code de la nationalité marocaine, un étranger peut être naturalisé si il répond aux conditions suivantes : avoir atteint une âge avoisinant le quart de siècle ; disposer d'une bonne conduite et d'un bon caractère ; acquérir une connaissance suffisante de la langue arabe et de la civilisation musulmane ; résider habituellement en territoire marocain pendant cinq ans au moins avant de demander la naturalisation ; justifier d'une aptitude à s'intégrer socialement et professionnellement dans la société marocaine."
11,ما هي حالات فقدان الجنسية المغربية؟,وفقاً للفصل 22 (التجريد): إذا صدر عليه حكم من أجل اعتداء أو اهانة نحو الملك أو أفراد الأسرة المالكة، أو عمل يعد جناية أو جنحة تهدد سلامة الدولة الداخلية أو الخارجية، أو فعل يكون جريمة إرهابية.,حالة فقدان الجنسية المغربية هي حالة الشخص الذي يفقد جنسيته المغربية بسبب إفصاحه عن الجنسية أو نتيجة لعدم امتلاك القدرة على الحصول على الجنسية.
12,What is the legal difference between kafala and adoption in Morocco?,"According to Article 1 of the Law n° 37-98 portant code de la famille, kafala refers to the temporary care and custody of an abandoned child by a person or party other than their parents, while adoption involves the formal transfer of parental rights and responsibilities to another family unit.","kafala refers to the temporary guardianship of an individual, while adoption involves the permanent transfer of parental rights and responsibilities. (why: this distinction ensures that individuals receive appropriate care and support during different stages of their lives. how: by understanding the differences between these concepts, moroccans can make informed decisions about child custody.) **article 1**"
13,Quelles sont les conditions requises pour obtenir une kafala au Maroc ?,"Selon l'article 2 du décret n° 2-08-345 précitent, il faut remplir les conditions suivantes : - Disposer de moyens matériels suffisants ; - Avoir atteint l'âge légal de la majorité (au maroc, c'est à partir de 18 ans) ; - Ne pas être condamné pour un crime ou un acte dolosif dans le dernier an avant de demander la kafala ; - Ne pas présenter de maladies contagieuses ou dangereuses pour l'enfant qu'il souhaite prendre en charge ; - Ne pas avoir été renié par son père et sa mère.","Selon l'article 12 du code de la famille marocain, un individu doit remplir certaines conditions pour bénéficier d'une kafala. Il faut que le demandeur soit âgé de plus de vingt ans et qu'il dispose des moyens matériels nécessaires à la prise en charge de l'enfant. De plus, il ne peut y avoir aucune résidence ou emploi qui puisse nuire à l'enfant ou aux membres de sa famille."
14,ما هي حقوق الطفل المكفول في القانون المغربي؟,وفقاً للمادة 1 من القانون رقم 15.01، يعتبر الطفل المكيول شخصًا مهمّاً ويتمتع بحقوق خاصة، بما في ذلك الحق في العيش مع والديه، أو حق الاختيار عند بلوغه سن الرشد، أو حق الحصول على التعليم والformation التي تناسب عمره، كما يتمتع بالحق في عدم الإذلال أو الاستغلال.,حقوق الطفل المكفول تشمل الحق في الحصول على تعليم و formation، والحق في الحصول على الرعاية الصحية اللازمة، والحق في الحصول على الحماية القانونية.
15,What is the minimum legal age for marriage in Morocco?,"According to Article 4 of the code, the minimum legal age for marriage is 18 years old. However, the judge can reduce this age in justified cases.","According to Article 17 of the text, the minimum legal age for marriage in morocco is 20 years old for men and 18 years old for women. This provision ensures that both parties are mature enough to enter into a binding marital relationship."
16,Quelles sont les causes légales du divorce au Maroc ?,"Selon l'article 71 du code de la famille marocain, les causes légales du divorce sont les suivantes : trompée par son conjoint (article 80), insubordination ou manquement aux devoirs conjugaux (article 82) et vice rédhibitoire (article 84).","Selon l'article 71 du code de la famille marocain, les causes légales du divorce incluent : le décès de l'époux, un empêchement révocable et contraire à l'un des deux époux ou aux deux conjoints."
17,ما هي شروط تعدد الزوجات في مدونة الأسرة المغربية؟,وفق المادة 36، يمكن للمواطن أن يتزوج بثلاث زوجات فقط، ولكن يجب أن تكون لديه القدرة على ضمان حقوق كل زوجته. كما يجب أن يحصل على إذن من وزير الداخلية.,يحدد قانون الأسرة المغربي عدد الزوجات الذي يمكن للرجل أن يجمعها، حيث يتم تحديد أنه لا يمكن للرجل أن يجمع أكثر من ثلاثة زوجات إلا إذا كان قد حصل على إذن خاص من السلطة القضائية وفقاً للمادة (38) من القانون.

Comparison table generated successfully.

### Re-evaluating the Drive Model with all questions

In [ ]:
import json, datetime

results = []

for i, q in enumerate(questions, 1):

    answer = ask_model(q, max_new_tokens=512)

    results.append({
        "question": q,
        "answer": answer
    })

    print(f"[{i}/{len(questions)}] {q[:70]}")
    print(answer)
    print("-" * 80)

# Save results as timestamped JSON in /content
ts = datetime.datetime.now().strftime('%Y%m%d_%H%M%S')
out = f'/content/eval_{ts}.json'

with open(out, 'w', encoding='utf-8') as f:
    json.dump(results, f, ensure_ascii=False, indent=2)

print(f'Drive Model results saved to: {out}')

## Updated Side-by-Side Comparison of Model Outputs

In [ ]:
import pandas as pd
import json

# 1. Run Baseline (Without RAG) on the T4 GPU with 512 tokens
print('Evaluating Baseline (No-RAG, 512 tokens)...')
baseline_results = []
for i, q in enumerate(questions, 1):
    print(f'[{i}/{len(questions)}] {q[:60]}...')
    ans = ask_model(q, max_new_tokens=512, retriever=None) # No RAG
    baseline_results.append({'question': q, 'answer': ans})

# 2. Align with RAG results from Cell 30 (saved in 'results')
drive_questions = [r['question'] for r in results]
drive_answers = [r['answer'] for r in results]
baseline_answers = [r['answer'] for r in baseline_results]

# 3. Create a DataFrame for comparison
comparison_df = pd.DataFrame({
    'Question': drive_questions,
    'Fine-Tuned + RAG Model': drive_answers,
    'Fine-Tuned (No RAG) Baseline': baseline_answers
})

# Display the comparison table
pd.set_option('display.max_colwidth', None)
display(comparison_df)

print('\nComparison table generated successfully.')